FROM eclipse-temurin21-jdk AS build
WORKDIR app

# Copy source code
COPY . .

# Build menggunakan gradlemaven
RUN .mvnw clean package -DskipTests

# Image runtime
FROM eclipse-temurin21-jre
WORKDIR app

# Copy hasil jar dari build
COPY --from=build apptarget.jar app.jar

EXPOSE 8080
ENTRYPOINT [java, -jar, app.jar]
